### ISSUE TITLE
Can I place ./issues/ in a Git submodule?

### ISSUE THREAD

**Issue by kajmagnus** [driusan/bug#19]
Hi, I'd like to be able to rewrite the history and do weird things, with the Issues project, a bit independently of the main project. So that I can give "lots of" people access to the issues repo, without fearing that someone will wreak havoc on the main & important repo.

Therefore I wonder, what if I place the `./issues/` dir in a separate Git repo, mounted as a Git submodule in the main repo? Will Bug still work fine, then?

B.t.w. this:

> you can also have multiple issues/ directories at different places in your directory tree

And to use those other *issues/* dirs, I'd `cd` to their parent dir, before invoking Bug? then Bug will use their dirs instead of the one in the project root?

**Comment by driusan** [comment]
Most of the commands should work fine, they just read/write files on the filesystem.

The only exceptions are "commit" and "purge", which interact with git. I'm not sure how they'd interact with git submodules. (The easiest thing to do would probably be to try them in a test repo and see.) If they don't work, it would be fairly easy to write a shell script that manages them outside of bug. (It would just need to do `git commit -a` for the equivalent of commit or `git clean -fd` for the equivalent of purge in the directory of `bug pwd`, and then update the submodule reference of the parent.)

The "bug" command walks up the filesystem tree until it finds an issues directory, and then uses that. (Similarly to how git looks for a `.git` directory or hg looks for a `.hg`). If you cd to the parent dir or any subdir it should use the closest issues directory to your current working directory.

(I'm closing this just because there's nothing actionable to do, feel free to keep asking any questions on this thread.)

**Comment by grantbow** [comment]
Has anyone tried this yet? The use of the PMIT environment variable to specify where to find files and the issues subdirectory may also be helpful to @kajmagnus .
